version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
    command: >
      bash -c "
        cd /app/ &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=${DEBUG:-True}
      - APP_LOGGING_LEVEL=${APP_LOGGING_LEVEL:-INFO}
      - DB_LOGGING_LEVEL=${DB_LOGGING_LEVEL:-INFO}
      - DJANGO_SETTINGS_MODULE=awsite.settings
      - APP=awsite
      - PYTHONDONTWRITEBYTECODE=1
      # forwarded from the host if they exist
      - UPDATE_PYTHON_REQUIREMENTS_ON_CONTAINERSTART
      - APP_FLAVOR=local
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always
    container_name: awsite_app

  postgres:
    restart: always
    volumes:
      - postgres123-data:/var/lib/postgresql/data/
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: awsite_db

volumes:
  postgres123-data: {}
